server:
  port: 8084
    
# My SQL #
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/banking?createDatabaseIfNotExist=true
    username: root
    password: VaxiDrez2005$
    driverClassName: com.mysql.cj.jdbc.Driver

#jdbc:mysql://localhost:3306/MS_02_2022_CLIENTES?serverTimezone=GMT-6

# Hibernate
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true

  
# Spring Boot Admin
  boot:
    admin:
      client:
        url: http://localhost:8890

# Registry Client
eureka:
   client:
      registryFetchIntervalSeconds: 5
      fetch-registry: true
      serviceUrl:
         defaultZone: http://localhost:8889/eureka

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
