
server:
  port: 8085
    
# MongoDB #
spring:
   data:
      mongodb:
         database: MS_02_2022_PEDIDOS_QUERY
#        username:
#        password:
         host: localhost
         port: 27017

# Registry Client
eureka:
   client:
      fetch-registry: true
      serviceUrl:
         defaultZone: http://localhost:8889/eureka
         
#Metrics related configurations
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    gateway:
      enabled: true   
  endpoints:
      web:
        exposure:
          include: "*"
  metrics:
    export:
      prometheus:
        enabled: true