server:
  port: 8883

spring:
  data:
    mongodb:
      uri: mongodb+srv://rcoronado:rcoronado@cluster0.pjt8oa9.mongodb.net/ahorros?retryWrites=true&w=majority 
      port: 27017    
      
  kafka:
    producer:
      bootstrap-servers: localhost:29092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      
      
  
# Spring Boot Admin
  boot:
    admin:
      client:
        url: http://localhost:8890

# Registry Client
eureka:
   client:
      registryFetchIntervalSeconds: 5
      fetch-registry: true
      serviceUrl:
         defaultZone: http://localhost:8889/eureka


# Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
 
