server:
  port: 8882
    
# My SQL #
spring:
#  datasource:    
#    url: jdbc:mysql://35.225.177.212:3306/banking?createDatabaseIfNotExist=true
#    username: root
#    password: Inside
#    driverClassName: com.mysql.cj.jdbc.Driver

##jdbc:mysql://localhost:3306/MS_02_2022_CLIENTES?serverTimezone=GMT-6
##jdbc:mysql://localhost:3306/db_empleados?createDatabaseIfNotExist=true
##VaxiDrez2005$
## Hibernate
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    generate-ddl: true


  datasource:
    url: jdbc:postgresql://35.199.98.199:5432/db_productos?createDatabaseIfNotExist=true
    username: postgres
    password: bdpostgreroot
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: update    

#jdbc:mysql://localhost:3306/MS_02_2022_CLIENTES?serverTimezone=GMT-6
#url: jdbc:mysql://localhost:3306/db_empleados?createDatabaseIfNotExist=true
#    username: root
#    password: VaxiDrez2005$
#    driverClassName: com.mysql.cj.jdbc.Driver


# Hibernate
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    generate-ddl: true

  
# Spring Boot Admin
  boot:
    admin:
      client:
        url: http://localhost:8890

# Registry Client
eureka:
   client:
      registryFetchIntervalSeconds: 5
      fetch-registry: true
      serviceUrl:
         defaultZone: http://localhost:8889/eureka

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
