
server:
  port: 8885
    
# MongoDB #
spring:
   data:
      mongodb:
         uri: mongodb+srv://rcoronado:rcoronado@cluster0.pjt8oa9.mongodb.net/cliente?retryWrites=true&w=majority
         database: Persona
#        username:
#        password:
#         host: localhost
         port: 27017

# Registry Client
eureka:
   client:
      fetch-registry: true
      serviceUrl:
         defaultZone: http://localhost:8889/eureka
         
#Metrics related configurations
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    gateway:
      enabled: true   
  endpoints:
      web:
        exposure:
          include: "*"
  metrics:
    export:
      prometheus:
        enabled: true